import { Component, OnInit } from '@angular/core';

interface Data {
  name: string;
  gender: string;
  age: number;
}

@Component({
  selector: 'app-table',
  templateUrl: './table.component.html',
  styleUrls: ['./table.component.css'],
})
export class TableComponent implements OnInit {
  data = [
    {
      activity: 'Volunteer at your local food pantry',
      type: 'charity',
      participants: 1,
      price: 0,
      link: '',
      key: '1878070',
      accessibility: 0.1,
    },
    {
      activity: "Resolve a problem you've been putting off",
      type: 'busywork',
      participants: 1,
      price: 0,
      link: '',
      key: '9999999',
      accessibility: 0,
    },
    {
      activity: 'Clean out your car',
      type: 'busywork',
      participants: 1,
      price: 0,
      link: '',
      key: '2896176',
      accessibility: 0.08,
    },
    {
      activity: 'Write a poem',
      type: 'recreational',
      participants: 1,
      price: 0,
      link: '',
      key: '8688620',
      accessibility: 0,
    },
    {
      activity: 'Create a personal website',
      type: 'recreational',
      participants: 1,
      price: 0.1,
      link: '',
      key: '3141417',
      accessibility: 0.12,
    },
    {
      activity: 'Learn the Chinese erhu',
      type: 'music',
      participants: 1,
      price: 0.6,
      link: '',
      key: '2742452',
      accessibility: 0.4,
    },
    {
      activity: 'Color',
      type: 'relaxation',
      participants: 1,
      price: 0.1,
      link: '',
      key: '5322987',
      accessibility: 0,
    },
    {
      activity: 'Draw something interesting',
      type: 'recreational',
      participants: 1,
      price: 0,
      link: '',
      key: '8033599',
      accessibility: 0,
    },
    {
      activity: 'Make tie dye shirts',
      type: 'diy',
      participants: 1,
      price: 0.2,
      link: '',
      key: '8092359',
      accessibility: 0.2,
    },
    {
      activity: 'Go to the gym',
      type: 'recreational',
      participants: 1,
      price: 0.2,
      link: '',
      key: '4387026',
      accessibility: 0.1,
    },
    {
      activity: 'Write a poem',
      type: 'recreational',
      participants: 1,
      price: 0,
      link: '',
      key: '8688620',
      accessibility: 0,
    },
    {
      activity: 'Listen to a new music genre',
      type: 'music',
      participants: 1,
      price: 0,
      link: '',
      key: '4708863',
      accessibility: 0,
    },
    {
      activity: 'Do something you used to do as a kid',
      type: 'relaxation',
      participants: 1,
      price: 0.1,
      link: '',
      key: '8827573',
      accessibility: 0.8,
    },
    {
      activity: 'Organize your movie collection',
      type: 'busywork',
      participants: 1,
      price: 0,
      link: '',
      key: '6378359',
      accessibility: 0,
    },
    {
      activity: 'Write a song',
      type: 'music',
      participants: 1,
      price: 0,
      link: '',
      key: '5188388',
      accessibility: 0,
    },
    {
      activity: 'Visit your past teachers',
      type: 'social',
      participants: 1,
      price: 0,
      link: '',
      key: '8238918',
      accessibility: 0.7,
    },
    {
      activity: 'Find a charity and donate to it',
      type: 'charity',
      participants: 1,
      price: 0.4,
      link: '',
      key: '1488053',
      accessibility: 0.1,
    },
    {
      activity: 'Learn how to play a new sport',
      type: 'recreational',
      participants: 1,
      price: 0.1,
      link: '',
      key: '5808228',
      accessibility: 0.2,
    },
    {
      activity: 'Learn the periodic table',
      type: 'education',
      participants: 1,
      price: 0,
      link: 'https://en.wikipedia.org/wiki/Periodic_table',
      key: '3621244',
      accessibility: 0.6,
    },
    {
      activity: 'Look at pictures and videos of cute animals',
      type: 'relaxation',
      participants: 1,
      price: 0,
      link: '',
      key: '2565076',
      accessibility: 1,
    },
    {
      activity: 'Read a formal research paper on an interesting subject',
      type: 'education',
      participants: 1,
      price: 0,
      link: '',
      key: '3352474',
      accessibility: 0.1,
    },
    {
      activity: 'Write a list of things you are grateful for',
      type: 'relaxation',
      participants: 1,
      price: 0,
      link: '',
      key: '2062010',
      accessibility: 0,
    },
    {
      activity: 'Learn how to french braid hair',
      type: 'education',
      participants: 1,
      price: 0,
      link: '',
      key: '8926492',
      accessibility: 0.1,
    },
    {
      activity: 'Learn how to french braid hair',
      type: 'education',
      participants: 1,
      price: 0,
      link: '',
      key: '8926492',
      accessibility: 0.1,
    },
    {
      activity: 'Improve your touch typing',
      type: 'busywork',
      participants: 1,
      price: 0,
      link: 'https://en.wikipedia.org/wiki/Touch_typing',
      key: '2526437',
      accessibility: 0.8,
    },
    {
      activity: 'Learn how to use an Arduino',
      type: 'education',
      participants: 1,
      price: 0.1,
      link: 'https://en.wikipedia.org/wiki/Arduino',
      key: '8264223',
      accessibility: 0.7,
    },
    {
      activity: 'Create a cookbook with your favorite recipes',
      type: 'cooking',
      participants: 1,
      price: 0,
      link: '',
      key: '1947449',
      accessibility: 0.05,
    },
    {
      activity: 'Volunteer at a local animal shelter',
      type: 'charity',
      participants: 1,
      price: 0.1,
      link: '',
      key: '1382389',
      accessibility: 0.5,
    },
    {
      activity: 'Write a short story',
      type: 'recreational',
      participants: 1,
      price: 0,
      link: '',
      key: '6301585',
      accessibility: 0.1,
    },
    {
      activity: 'Buy a new house decoration',
      type: 'recreational',
      participants: 1,
      price: 0.4,
      link: '',
      key: '3456114',
      accessibility: 0.3,
    },
  ];

  className = 'bgGreen';

  constructor() {}

  ngOnInit(): void {}

  onDelete(index: number) {
    this.data = this.data.filter((item, i) => i !== index);
  }

  trackByFunction(item) {
    return item.key;
  }
}
